### ISSUE TITLE
exit smart shift keychord mode automatically?

### ISSUE THREAD

**Issue by ghost** [hbin/smart-shift#7]
Hello and thanks for this package.

I bound keys to do `smart-shift-left / right`

But when I press them I stay in 'smart shift keychord' mode and must press C-g to exit.

I wonder how to exit automatically this keychord mode, after i invoked by binding, or after a short delay without inputs.

If not possible is there alternatives? I do not use indent-rigidly keybinds because not all my files use same indentation size.

thanks!

**Comment by tcw165** [comment]
Hi Anis,

I haven't touched the Emac Lisp for years and I'm afraid that I couldn't
answer your question.

Cheers,
TC

**Comment by ghost** [comment]
Hi TC, ok no worries. thanks for replying at least.
